name: Update ECHO data

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}

    steps:
      - name: Run ECHO Scrape
        run: |
          npm install
          npm run echo